/*
How many hours did you spend on this assignment?:
5 hours 
What part of the assignment did you spend the most time on?:
Refactoring, developing reponses for the winning/losing conditions
How comfortable did you feel with this assignment? (1-5):
3
Is there anything in this code that you feel pleased about?:
Refactoring; making code shorter and simpler; familiarising more with functions
What's one aspect of your code you would like specific, elaborate feedback on?:
How to make it to the most comfortable version
*/

// Objects
var SCISSORS = "scissors";
var PAPER = "paper";
var STONE = "stone";

// Players
var AI = "ai";

// ---Outcomes---
var WIN = "You win";
var LOST = "You lost";
var DRAW = "You draw";

// Personalising game with user's name
var userName = "";

// Initialise the number of player wins, computer wins, and draws to 0.
var numPlayerWins = 0;
var numAIWins = 0;
var numDraws = 0;

// Win Rate
var winRate;

//Generating computer AI's option randomly
var generateRockPaperScissorsOption = function () {
  var randomNumber = Math.floor(Math.random() * 3);
  if (randomNumber == 0) {
    return STONE;
  }
  if (randomNumber == 1) {
    return PAPER;
  }
  return SCISSORS;
};
//Helper funtion for userWinAi conditions
var userWinAi = function (inputTrim, aiChoice) {
  return (
    (inputTrim == SCISSORS && aiChoice == PAPER) ||
    (inputTrim == PAPER && aiChoice == STONE) ||
    (inputTrim == STONE && aiChoice == SCISSORS)
  );
};

//Stage 1:
//Colllecting user name info
//Input your name to start game; "How would you like to be called?"
//
var main = function (input, name) {
  if (!userName) {
    if (!name) {
      return "Please input name!";
    }
    userName = name;
    return "Welcome, " + userName;
  }
  playerChoice = input;
  // trim input to lowercase and removespaces
  var inputTrim = input.toLowerCase().trim();
  //checks for validity of input
  if (inputTrim != "scissors" && inputTrim != "paper" && inputTrim != "stone") {
    //informs user to enter a valid input
    return 'Your input is invalid. Please enter either "scissors", "paper", "stone".';
  }
  var aiChoice = generateRockPaperScissorsOption();

  if (userWinAi(inputTrim, aiChoice)) {
    myOutputValue = WIN;
    numPlayerWins = numPlayerWins + 1;
  } else if (aiChoice == inputTrim) {
    myOutputValue = DRAW;
    numDraws = numDraws + 1;
  } else {
    myOutputValue = LOST;
    numAIWins = numAIWins + 1;
  }
  //output var as string
  return (
    `${myOutputValue} you chose ${inputTrim} and the AI chose ${aiChoice}` +
    "<br>" +
    userName +
    ": " +
    numPlayerWins +
    " | Computer: " +
    numAIWins +
    " | Draws: " +
    numDraws
  );
};

// return inputTrim;
// return myOutputValue:
//"How would you like to be called? Type your name to start the game" (include in html)
//Input will be Rock Scissors Paper
//Output is generated by computer and function "generateRockPaperScissorsOption"
////How many different cases are there? Three; AI win, user win; draw
//Draw a simple flowchart to help you visualise the overall control flow of the program.

//   var aiChoice = generateRockPaperScissorsOption();
//   if (aiChoice == SCISSORS && inputTrim == PAPER) {
//     myOutputValue = LOST;
//     console.log(myOutputValue);
//   }
// if (aiChoice == PAPER && inputTrim == SCISSORS) {
//     myOutputValue = WIN;

// userWinAi(inputTrim, aiChoice);

//Output will be
//User Chose ""
//AI: Chose ""
// Either AI or User won. Congrats "you won" or "sorry you lost"
// Can include counter of times played:, Wins: (no. and % if time permit), losses (no. and %) and Ties (no. and %)
var outputWinLossMessage = function () {
  return (
    "<br>" +
    userName +
    ": " +
    numPlayerWins +
    " | Computer: " +
    numAIWins +
    " | Draws: "
  );
};

/*
How many hours did you spend on this assignment?:
3 (so far)
What part of the assignment did you spend the most time on?:
Logic of the conditions

How comfortable did you feel with this assignment? (1-5):
1
Is there anything in this code that you feel pleased about?:
None
What's one aspect of your code you would like specific, elaborate feedback on?:

*/

//   var aiChoice = generateRockPaperScissorsOption();
//   if (aiChoice == SCISSORS && inputTrim == PAPER) {
//     myOutputValue = LOST;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == SCISSORS && inputTrim == STONE) {
//     myOutputValue = WIN;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == SCISSORS && inputTrim == SCISSORS) {
//     myOutputValue = DRAW;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == PAPER && inputTrim == PAPER) {
//     myOutputValue = DRAW;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == PAPER && inputTrim == STONE) {
//     myOutputValue = LOST;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == PAPER && inputTrim == SCISSORS) {
//     myOutputValue = WIN;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == STONE && inputTrim == PAPER) {
//     myOutputValue = WIN;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == STONE && inputTrim == STONE) {
//     myOutputValue = DRAW;
//     console.log(myOutputValue);
//   }
//   if (aiChoice == STONE && inputTrim == SCISSORS) {
//     myOutputValue = LOST;
//     console.log(myOutputValue);
//   }
//   //output var as string
//   return `${myOutputValue} you chose ${inputTrim} and the AI chose ${aiChoice}`;
// };
